See [qtl2shiny/inst/scripts
/network_igraph.Rmd](https://github.com/byandell/qtl2shiny/blob/master/inst/scripts/network_igraph.Rmd) for more ways to plot. Can also make interactive.

```{r message=FALSE}
nodes <- 
  readr::read_csv(system.file("data/foundrNode.csv", package = "foundrShiny"),
                  comment = "#") |>
  dplyr::filter(origin %in% c("server","panel","module"))
links <- 
  readr::read_csv(system.file("data/foundrEdge.csv", package = "foundrShiny"),
                  comment = "#") |>
  dplyr::filter(assign %in% c("module","arg"))
```

```{r eval=FALSE}
ulinks <- sort(unique(c(links$source, links$target)))
unodes <- sort(unique(nodes$node))
m <- match(ulinks, unodes)
ulinks[which(is.na(m))]
mm <- match(unodes, ulinks)
unodes[which(is.na(mm))]
```

```{r eval=FALSE}
out <- links %>% filter(!(source %in% c("output","input")), !(target %in% c("output","input"))) %>%
  mutate(origin = source)
out <- bind_rows(
  out %>% select(-target),
  out %>% select(-source) %>% rename(source = "target")) %>%
  distinct(origin, source, assign) %>%
  arrange(assign, origin, source) %>%
  rename(node = "source", type = "assign")

readr::write_csv(out, "inst/extdata/out.csv")
```

```{r}
net <- igraph::graph_from_data_frame(d=links, vertices=nodes, directed=TRUE)
```

```{r}
net <- igraph::simplify(net, remove.multiple = F, remove.loops = TRUE) 
```

```{r}
plot(net, 
     edge.arrow.size = 0.4,
     vertex.label = NA)
```

```{r}
# Generate colors based on media type:
colrs <- c("skyblue", "gold", "tomato", "lightgrey","lightgreen")
igraph::V(net)$color <- colrs[factor(igraph::V(net)$origin)]

# Compute node degree (#links) and use it to set node size:
deg <- igraph::degree(net, mode="all")
igraph::V(net)$size <- sqrt(deg)*10
#V(net)$size <- V(net)$audience.size*0.6

# The labels are currently node IDs.
# Setting them to NA will render no labels:
igraph::V(net)$label.color <- "black"
igraph::V(net)$label[igraph::V(net)$origin == "module"] <- NA
igraph::V(net)$label[igraph::V(net)$origin != "module"] <-
  toupper(stringr::str_extract(names(igraph::V(net))[igraph::V(net)$origin != "module"], "^.{1}"))
igraph::V(net)$label[names(igraph::V(net)) == "trait"] <- "R"

# Set edge width based on weight:
#E(net)$width <- E(net)$weight/6

#change arrow size and edge color:
igraph::E(net)$arrow.size <- .4
igraph::E(net)$edge.color <- "black"

plot(net) 
```

```{r}
print(net, full = TRUE)
```

```{r}
netPanel <- 
  igraph::subgraph.edges(net, c(1:4))
plot(netPanel)
```

```{r}
netTrait <- 
  igraph::subgraph.edges(net, c(1, 25:37))
plot(netTrait)
```

```{r}
netContrast <- 
  igraph::subgraph.edges(net, c(2, 5:17))
plot(netContrast)
```

```{r}
netStats <- 
  igraph::subgraph.edges(net, c(3, 18))
plot(netStats)
```

```{r}
netTime <- 
  igraph::subgraph.edges(net, c(4, 19:24))
plot(netTime)
```


```{r}
plot(net) 
legend(2,0,legend = levels(factor(V(net)$origin)), 
       pch = 21,
       col = "#777777", pt.bg = colrs, 
       pt.cex = 1, 
       bty = "n", ncol = 1)
```

```{r}
#change arrow size and edge color:
igraph::E(net)$arrow.size <- .2
igraph::E(net)$edge.color <- "gray80"
```

```{r}
netCore <- 
  igraph::delete_vertices(
    igraph::delete_edges(
      net,
      igraph::E(net)[assign == "arg"]),
    unclass(igraph::V(net)[origin == "module"]))
```

```{r eval=FALSE}
netTrait <- 
  igraph::delete_vertices(
    igraph::delete_edges(
      net,
      igraph::E(net)[assign == "arg"]),
    unclass(igraph::V(net)[origin == "module"]))
```

```{r}
netModule <-
  igraph::delete_vertices(
    igraph::delete_edges(
      net,
      igraph::E(net)[assign == "arg"]),
    unclass(igraph::V(net)[origin == "server"]))
```

```{r}
plot(net)
```

```{r}
plot(netCore)
```

```{r message=FALSE, warning=FALSE, fig.width=7, fig.height=7}
#jpeg("net.jpg", width = 700, height = 700)
plot(netModule, vertex.shape="none", 
     vertex.label=igraph::V(netModule)$name, 
     vertex.label.font=2, vertex.label.color="black",
     vertex.label.cex=0.5, edge.color="gray50",
     layout = igraph::layout_as_tree)
#invisible(dev.off())
```